# Main Configes
url: http://mrk1869.com
product_url: http://mrk1869.com
title: Markovnikov Laboratory
author: Shoya Ishimaru
descliption: Weblog by Mrk1869

#permalink: /:category/:year-:month-:day/:title
permalink: /:categories/:title/
paginate: 3 # the number of post per page
pygments: true
